### ISSUE TITLE
Why is `EvalResult.obj` an `Array{Float64}`?

### ISSUE THREAD

**Issue by ferrolho** [JuliaOpt/KNITRO.jl#113]
As far as I know, KNITRO can only evaluate cost/objective functions that result in a single value. As such, why is it that `EvalResult.obj` is an `Array`?

https://github.com/JuliaOpt/KNITRO.jl/blob/5caf23741fff6792ffec858907885aebebe2e5fd/src/kn_callbacks.jl#L259-L269

My apologies in advance if this question is not directly related to `KNITRO.jl` but to KNITRO itself; but this is really the best place I could remember for asking such a question...

**Comment by frapac** [comment]
No worry! The reason is that in Knitro, we are passing the objective as a pointer to the different callbacks (see for instance [Knitro documentation about callbacks](https://www.artelys.com/tools/knitro_doc/2_userGuide/callbacks.html)). In KNITRO.jl, `EvalResult` is a direct wrapper to the C object `KN_eval_result`, and as so store the objective as `Array{Float64}`. 

This allows to mimic the behavior of C callbacks in Julia, for instance: 
```
*obj = 100.0 * (dTmp*dTmp) + ((1.0 - x[0])*(1.0 - x[0]));
``` 

But I agree with  you, Knitro does not support multiobjective optimization.

**Comment by ferrolho** [comment]
So, in a nutshell, this is just a way of easing the wrappers for the C callbacks?

**Comment by frapac** [comment]
Exactly. And also to add consistency between the different Knitro interfaces.
