### ISSUE TITLE
Why is `nV` a parameter of `KN_set_cb_grad()`?

### ISSUE THREAD

**Issue by ferrolho** [JuliaOpt/KNITRO.jl#161]
The signature of `KN_set_cb_grad()` consists of `nV` and `objGradIndexVars`, among other parameters:
https://github.com/JuliaOpt/KNITRO.jl/blob/d6002d40b59e80b19c9d93f3dc3942a4d3249866/src/kn_callbacks.jl#L413-L415
I am wondering why `nV` is part of the function signature when it could be obtained within the function as `length(objGradIndexVars)` instead. Is this redundancy there on purpose?

Indeed it seems there is an `assert` to check for `nV` and `objGradIndexVars` consistency:
https://github.com/JuliaOpt/KNITRO.jl/blob/d6002d40b59e80b19c9d93f3dc3942a4d3249866/src/kn_callbacks.jl#L420

**Comment by frapac** [comment]
Good question! I acknowledge that Knitro's API is sometimes mysterious, but that's the price for its flexibility I guess. Here, different situations could occur: 

- you do not want to compute the gradient of the objective in this particular callback environment `cb` (e.g. if your objective is linear, or computed in another callback environment). Then, set `nV = 0` 
- the gradient of your objective is dense, and hence you do not want to specify all the sparsity pattern: then, set `nV=KN_DENSE` (with `KN_DENSE` being equal to `-1` as far as I remember)
- otherwise, the gradient of your objective is sparse and you have to specify the sparsity pattern appart with `objGradIndexVars`; `nV` should be equal to the number of non-zero components in the gradient. 

There might exist a simpler solution, though. Maybe by defining different functions (`KN_set_cb_dense_grad`, `KN_set_cb_sparse_grad`, ...), but this is a non-trivial task and we have to be careful about being non-redundant with the C API. Anyway, I am open to any suggestion!

In any case, you make a point. I think it would be nice to add some documentation to better explain how to pass callbacks to Knitro.

**Comment by ferrolho** [comment]
Thanks for the answer! I understand the points you've listed and the current approach may not be that bad after all. :slightly_smiling_face:
