### ISSUE TITLE
Memory allocation for a license from the Ziena License Manager for high volume KNITRO applications

### ISSUE THREAD

**Issue by pierremabille** [JuliaOpt/KNITRO.jl#58]
Does it work? The methods are commented in https://github.com/JuliaOpt/KNITRO.jl/blob/master/src/ktr_functions.jl#L70. I gave it a try on a computer cluster, on which I need to solve a very large number of nonlinear systems, but with no success. Thanks.

**Comment by yeesian** [comment]
We'd be happy to accept a PR if you figure it out, and will like to submit one (:

**Comment by pierremabille** [comment]
Did you guys give it a try? I haven't been able to figure it out. The checkoutlicense and releaselicense methods should be updated, but I don't know how. In particular @zlm_ccall is not defined inside the code, what does it refer to?

**Comment by yeesian** [comment]
The `@zlm_ccall` macro has not yet been defined, since it isn't yet required anywhere. If it were to be defined, it'll be analogous to [that for `ktr_ccall`](https://github.com/JuliaOpt/KNITRO.jl/blob/master/src/KNITRO.jl#L28-L35). Figuring it out will be a good entry point for you to understand the KNITRO codebase.

**Comment by pierremabille** [comment]
I and other people figured it out. Will try to post an explanation here in the next month or so, then perhaps a pull request.

**Comment by frapac** [comment]
This is adressed for KNITRO 11 in #94
